import Foundation
import SwiftUI

enum AppTheme {
    static let canvas = Color(red: 0.055, green: 0.063, blue: 0.082)
    static let panel = Color(red: 0.101, green: 0.117, blue: 0.149)
    static let panelSecondary = Color(red: 0.125, green: 0.145, blue: 0.184)
    static let sidebarTop = Color(red: 0.125, green: 0.196, blue: 0.286)
    static let sidebarBottom = Color(red: 0.066, green: 0.111, blue: 0.152)
    static let accent = Color(red: 0.360, green: 0.643, blue: 0.933)
    static let accentSoft = Color(red: 0.258, green: 0.470, blue: 0.721)
    static let success = Color(red: 0.255, green: 0.741, blue: 0.541)
    static let warning = Color(red: 0.984, green: 0.639, blue: 0.302)
    static let border = Color.white.opacity(0.085)
    static let subtleBorder = Color.white.opacity(0.040)
    static let secondaryText = Color.white.opacity(0.64)
    static let tertiaryText = Color.white.opacity(0.42)

    static let sidebarGradient = LinearGradient(
        colors: [sidebarTop, sidebarBottom],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    static let panelGradient = LinearGradient(
        colors: [panelSecondary, panel],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
}

enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case english = "en"
    case chinese = "zh-Hans"
    case italian = "it"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english:
            return "English"
        case .chinese:
            return "中文"
        case .italian:
            return "Italiano"
        }
    }

    var locale: Locale {
        Locale(identifier: rawValue)
    }

    static func bestMatch(for preferredLanguages: [String] = Locale.preferredLanguages) -> AppLanguage {
        for identifier in preferredLanguages {
            let lowercased = identifier.lowercased()
            if lowercased.hasPrefix("zh") {
                return .chinese
            }
            if lowercased.hasPrefix("it") {
                return .italian
            }
            if lowercased.hasPrefix("en") {
                return .english
            }
        }

        return .english
    }
}

enum AppText {
    static func value(_ key: String, language: AppLanguage, arguments: [CVarArg] = []) -> String {
        let format = translations[language]?[key] ?? translations[.english]?[key] ?? key
        guard !arguments.isEmpty else {
            return format
        }
        return String(format: format, locale: language.locale, arguments: arguments)
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .english: [
            "conversation.new": "New Chat",
            "preview.empty": "No messages yet",
            "preview.preparing": "Preparing reply...",
            "task.status.pending": "Pending",
            "task.status.running": "Running",
            "task.status.completed": "Completed",
            "sidebar.tagline": "Your macOS AI Agent workspace",
            "sidebar.newConversation": "New Chat",
            "sidebar.sessions": "Sessions",
            "sidebar.deleteConversation": "Delete Chat",
            "sidebar.pendingTasks": "Tasks %d",
            "sidebar.settings": "Settings",
            "sidebar.workspace": "Workspace: %@",
            "chat.requestFailed": "Request Failed",
            "common.ok": "OK",
            "chat.defaultTitle": "Start Building",
            "chat.readySubtitle": "OpenAI / DeepSeek compatible APIs supported with streaming replies.",
            "chat.setupSubtitle": "Open Settings, fill in the API config, and then start chatting.",
            "chat.tasks": "Tasks",
            "chat.newConversation": "New Chat",
            "composer.title": "Message",
            "composer.streaming": "Streaming",
            "composer.multiTurn": "Multi-turn chat enabled",
            "composer.task": "Task",
            "composer.stop": "Stop",
            "composer.send": "Send",
            "empty.title": "Start Building",
            "empty.readyDescription": "Type a message to start chatting, or send your idea to the task center and let the Agent execute it.",
            "empty.setupDescription": "Fill in your API information in Settings first, then streaming chat will be available.",
            "empty.openAgent": "Open Agent",
            "empty.openTaskCenter": "Open Task Center",
            "empty.openSettings": "Open Settings",
            "message.you": "You",
            "message.ai": "AI",
            "message.generating": "Generating step by step...",
            "taskCenter.title": "Task Center",
            "taskCenter.subtitle": "Save the current idea as a task, or hand it directly to the model. Running tasks are written back into chat automatically.",
            "common.close": "Close",
            "taskCenter.newTask": "New Task",
            "taskCenter.taskTitleHint": "Task title (optional)",
            "taskCenter.prefillTip": "Tip: if the chat composer already has content, opening this panel will prefill it automatically.",
            "taskCenter.createTask": "Create Task",
            "task.section.pending": "Pending",
            "task.section.completed": "Completed",
            "task.none.pending": "No pending tasks yet.",
            "task.none.completed": "No completed tasks yet.",
            "task.button.run": "Run Task",
            "task.button.rerun": "Run Again",
            "task.button.markComplete": "Mark Complete",
            "task.button.markIncomplete": "Mark Incomplete",
            "task.linkedConversation": "Chat: %@",
            "agent.title": "Local Agent",
            "agent.subtitle": "After choosing a workspace, the agent can create files, edit code, run commands, and self-check locally.",
            "agent.note": "It references long-term memory and the user knowledge base; code-like files are syntax prevalidated before being written.",
            "agent.workspace": "Workspace",
            "agent.workspace.none": "No workspace selected yet. You can use the default desktop workspace or choose an existing project folder manually.",
            "agent.useDesktop": "Use Desktop Workspace",
            "agent.chooseFolder": "Choose Folder",
            "agent.openFinder": "Open in Finder",
            "agent.goal": "Automation Goal",
            "agent.goalExample": "Example: build a runnable 2D game in the current workspace, then next time continue from the existing code with collisions, score, and menus.",
            "agent.lastSummary": "Last completion summary: %@",
            "agent.running": "Running...",
            "agent.start": "Start Automation",
            "agent.clearLogs": "Clear Logs",
            "agent.logs": "Execution Logs",
            "agent.noLogs": "No execution logs yet. After you start an automation task, file creation, command output, and self-check results will appear here.",
            "agent.pickWorkspacePrompt": "Choose Workspace",
            "settings.language.title": "Language",
            "settings.language.subtitle": "Switch the app language instantly. This affects the main interface and the first-use guide.",
            "settings.onboarding.title": "Guide",
            "settings.onboarding.subtitle": "Reopen the onboarding guide at any time if you want to review the workflow.",
            "settings.onboarding.reopen": "Show Guide Again",
            "settings.api.title": "API Settings",
            "settings.api.subtitle": "Supports OpenAI / DeepSeek compatible APIs. You can enter the full endpoint, or stop at `v1` and the app will complete it to `chat/completions` automatically.",
            "settings.api.urlHint": "For example https://api.openai.com/v1/chat/completions",
            "settings.api.reveal": "Show",
            "settings.api.hide": "Hide",
            "settings.modelName": "Model Name",
            "settings.modelNameHint": "For example gpt-4o-mini / deepseek-chat",
            "settings.api.save": "Save Configuration",
            "settings.api.complete": "Configuration is complete. Requests can be sent now.",
            "settings.api.incomplete": "Configuration is still incomplete.",
            "settings.compatibility": "Compatibility",
            "settings.compatibility.1": "1. Common OpenAI endpoint: `https://api.openai.com/v1/chat/completions`",
            "settings.compatibility.2": "2. Common DeepSeek endpoint: `https://api.deepseek.com/chat/completions`",
            "settings.compatibility.3": "3. If you use a self-hosted compatible gateway, you can also enter the full POST endpoint directly.",
            "settings.knowledge.title": "Knowledge Base",
            "settings.knowledge.subtitle": "This is a user-maintained knowledge base. You can store rules, business context, API notes, and style requirements. Both chat and the agent will automatically use it.",
            "settings.knowledge.entryTitle": "Knowledge Base Title",
            "settings.knowledge.entryHint": "For example: project rules / gameplay rules / API integration notes",
            "settings.knowledge.content": "Knowledge Base Content",
            "settings.knowledge.save": "Save to Knowledge Base",
            "settings.knowledge.update": "Update Knowledge Base",
            "settings.knowledge.clearEditor": "Clear Editor",
            "settings.knowledge.clearAll": "Clear Knowledge Base",
            "settings.knowledge.empty": "No knowledge base entries yet.",
            "common.edit": "Edit",
            "common.delete": "Delete",
            "settings.memory.title": "Long-Term Memory",
            "settings.memory.subtitle": "The app learns long-term preferences from your inputs and Agent tasks, and keeps using them in later chats and automations.",
            "settings.memory.empty": "No long-term memory learned yet.",
            "settings.memory.source": "Source: %@ · %@",
            "settings.memory.clear": "Clear Learned Memory",
            "settings.data.title": "Data Management",
            "settings.data.subtitle": "This button only clears local chats, tasks, logs, learned memory, and workspace references. It will not delete your API settings. To remove API data, clear the fields here and save again.",
            "settings.data.kbNote": "The knowledge base is also part of local data and will be cleared too, but your real project files in the desktop workspace will not be deleted.",
            "settings.data.clear": "Clear Local Data (Keep API)",
            "onboarding.badge": "First-time Guide",
            "onboarding.title": "Build Faster With Your Agent",
            "onboarding.subtitle": "This guide appears only on first launch. Later, you can reopen it from Settings anytime.",
            "onboarding.language.title": "Choose Language",
            "onboarding.language.subtitle": "Switch the interface language before you start.",
            "onboarding.step1.title": "1. Fill In API Settings",
            "onboarding.step1.body": "Open Settings and enter your API URL, API Key, and model name. OpenAI-compatible and DeepSeek-compatible endpoints are both supported.",
            "onboarding.step2.title": "2. Chat Or Create Tasks",
            "onboarding.step2.body": "Use the center chat view for normal multi-turn conversations. If you already know the target, open Task Center and save it as a task.",
            "onboarding.step3.title": "3. Use Local Agent Mode",
            "onboarding.step3.body": "Open Agent mode, pick a workspace, and describe the result you want. The agent can create folders, generate many file types, run commands, and continue iterating on existing code.",
            "onboarding.step4.title": "4. Let It Learn",
            "onboarding.step4.body": "Store rules in the knowledge base, and the app will also retain long-term memory from your requests so the agent becomes more consistent over time.",
            "onboarding.tip": "For code files, the agent now performs available syntax validation before writing whenever possible.",
            "onboarding.start": "Start Using OpenDesk",
            "onboarding.close": "Close Guide",
            "status.configurationSaved": "Configuration saved",
            "status.workspaceConnected": "Workspace connected",
            "status.desktopWorkspaceReady": "Desktop workspace is ready",
            "error.selectWorkspaceFirst": "Please choose a workspace first.",
            "error.kbEmpty": "Knowledge base title and content cannot both be empty.",
            "status.kbSaved": "Knowledge base saved",
            "status.localDataCleared": "Local data cleared. API settings were kept.",
            "status.stopping": "Stopping...",
            "error.taskEmpty": "Task content cannot be empty.",
            "task.newTaskFallback": "New Task",
            "status.taskCreated": "Task created",
            "error.agentRunning": "The agent is running. Please wait for it to finish or stop it first.",
            "error.replyRunning": "A reply is still being generated. Please wait or click stop first.",
            "error.agentGoalEmpty": "Please enter an automation goal.",
            "error.apiIncomplete": "Please fill in API URL, API Key, and model name in Settings first.",
            "error.chatRunning": "A normal chat response is still running. Please wait or stop it first.",
            "error.agentAlreadyRunning": "The agent is already running.",
            "error.createWorkspaceFailed": "Unable to create the desktop workspace.",
            "agent.log.goal": "Goal",
            "agent.log.workspace": "Workspace",
            "status.agentRunning": "Agent is running...",
            "status.agentDone": "Agent task completed",
            "status.agentStopped": "Agent stopped",
            "agent.log.interrupted.title": "Task Interrupted",
            "agent.log.interrupted.detail": "This automation run was stopped.",
            "agent.log.runFailed": "Run Failed",
            "status.stoppingAgent": "Stopping agent...",
            "error.settingsFirst": "Please open Settings and fill in the API URL, API Key, and model name first.",
            "status.generatingReply": "Generating reply...",
            "status.replyDone": "Reply completed",
            "error.emptyModelResponse": "The model returned empty content.",
            "status.replyStopped": "Generation stopped",
            "error.taskCancelled": "Task cancelled",
            "prompt.task.execute": "Please treat the following content as a task to complete.",
            "prompt.task.title": "Task Title:",
            "prompt.task.detail": "Task Detail:",
            "prompt.task.requirements": "Output Requirements:\n1. Start solving directly and do not repeat the title.\n2. If you need assumptions, state them clearly first and then continue.\n3. End with a short \"Result Summary\" section.",
            "prompt.system.memoryKB": "The following context comes from long-term memory and the user knowledge base. Please keep following it when possible:\n%@",
            "conversation.agentTaskFallback": "Agent Task",
            "conversation.agentGoal": "Agent goal: %@\nWorkspace: %@",
            "conversation.agentDone": "Agent execution completed.\n\n%@",
            "conversation.validationExitCode": "\n\nValidation exit code: %d\n",
            "prompt.context.memory": "Long-term Memory:\n%@",
            "prompt.context.kb": "User Knowledge Base:\n%@",
            "status.onboardingComplete": "Guide completed",
            "api.error.invalidURL": "The API URL is invalid. Please check the address in Settings.",
            "api.error.invalidResponse": "The server returned unreadable data.",
            "api.error.requestFailed": "Request failed (%d): %@",
            "api.error.emptyResponse": "The model returned no content.",
            "workspace.error.invalidPath": "The workspace path is invalid.",
            "workspace.error.outsideWorkspace": "The target path is outside the current workspace.",
            "workspace.error.readFailed": "Failed to read file: %@",
            "workspace.error.writeFailed": "Failed to write file: %@",
            "agent.error.invalidPlan": "The agent plan format is invalid: %@",
            "agent.error.exhaustedIterations": "The agent reached the maximum number of iterations and may not be fully finished yet.",
            "error.localSaveFailed": "Local save failed: %@"
        ],
        .chinese: [
            "conversation.new": "新对话",
            "preview.empty": "还没有消息",
            "preview.preparing": "正在准备回复...",
            "task.status.pending": "待执行",
            "task.status.running": "执行中",
            "task.status.completed": "已完成",
            "sidebar.tagline": "你的 macOS AI Agent 工作台",
            "sidebar.newConversation": "新建会话",
            "sidebar.sessions": "会话",
            "sidebar.deleteConversation": "删除会话",
            "sidebar.pendingTasks": "待办任务 %d",
            "sidebar.settings": "设置",
            "sidebar.workspace": "工作区：%@",
            "chat.requestFailed": "请求失败",
            "common.ok": "知道了",
            "chat.defaultTitle": "开始构建",
            "chat.readySubtitle": "支持 OpenAI / DeepSeek 格式接口，回复将流式刷新。",
            "chat.setupSubtitle": "先打开设置填好 API 配置，然后就可以开始对话。",
            "chat.tasks": "任务",
            "chat.newConversation": "新会话",
            "composer.title": "输入消息",
            "composer.streaming": "流式输出中",
            "composer.multiTurn": "支持多轮对话",
            "composer.task": "任务",
            "composer.stop": "停止",
            "composer.send": "发送",
            "empty.title": "开始构建",
            "empty.readyDescription": "直接输入消息开始对话，或把想法丢进任务中心交给 Agent 执行。",
            "empty.setupDescription": "先去设置里填好 API 信息，然后就能开始流式对话。",
            "empty.openAgent": "打开 Agent",
            "empty.openTaskCenter": "打开任务中心",
            "empty.openSettings": "打开设置",
            "message.you": "你",
            "message.ai": "AI",
            "message.generating": "正在逐步生成...",
            "taskCenter.title": "任务中心",
            "taskCenter.subtitle": "把当前思路存成任务，或直接交给模型执行。执行中的任务会自动写入会话。",
            "common.close": "关闭",
            "taskCenter.newTask": "新建任务",
            "taskCenter.taskTitleHint": "任务标题（可选）",
            "taskCenter.prefillTip": "提示：如果聊天输入框里已经有内容，打开这里时会自动带进来。",
            "taskCenter.createTask": "创建任务",
            "task.section.pending": "待处理",
            "task.section.completed": "已完成",
            "task.none.pending": "暂时没有待处理任务。",
            "task.none.completed": "暂时没有已完成任务。",
            "task.button.run": "执行任务",
            "task.button.rerun": "再次执行",
            "task.button.markComplete": "标记完成",
            "task.button.markIncomplete": "标记未完成",
            "task.linkedConversation": "会话：%@",
            "agent.title": "本地 Agent",
            "agent.subtitle": "选择一个工作区后，智能体可以直接在本地创建文件、改代码、执行命令并自动自检。",
            "agent.note": "它会同时参考长期记忆和用户知识库；代码类文件在落盘前会先做可用的语法预校验。",
            "agent.workspace": "工作区",
            "agent.workspace.none": "还没有选择工作区。你可以直接使用桌面默认工作区，或者手动选一个已有项目文件夹。",
            "agent.useDesktop": "使用桌面工作区",
            "agent.chooseFolder": "选择文件夹",
            "agent.openFinder": "在 Finder 打开",
            "agent.goal": "自动化目标",
            "agent.goalExample": "示例：在当前工作区生成一个可运行的 2D 小游戏；下次继续在原代码基础上加碰撞、积分和菜单。",
            "agent.lastSummary": "上次完成摘要：%@",
            "agent.running": "执行中...",
            "agent.start": "开始自动执行",
            "agent.clearLogs": "清空日志",
            "agent.logs": "执行日志",
            "agent.noLogs": "还没有执行日志。开始一次自动化任务后，这里会显示文件创建、命令输出和自检结果。",
            "agent.pickWorkspacePrompt": "选择工作区",
            "settings.language.title": "语言",
            "settings.language.subtitle": "即时切换应用语言。主界面和首次引导都会跟着切换。",
            "settings.onboarding.title": "使用引导",
            "settings.onboarding.subtitle": "如果你想再看一遍操作流程，可以随时在这里重新打开。",
            "settings.onboarding.reopen": "重新查看引导",
            "settings.api.title": "API 设置",
            "settings.api.subtitle": "支持 OpenAI / DeepSeek 兼容接口。你可以填完整接口地址，也可以填到 `v1` 为止，应用会自动补全到 `chat/completions`。",
            "settings.api.urlHint": "例如 https://api.openai.com/v1/chat/completions",
            "settings.api.reveal": "显示",
            "settings.api.hide": "隐藏",
            "settings.modelName": "模型名称",
            "settings.modelNameHint": "例如 gpt-4o-mini / deepseek-chat",
            "settings.api.save": "保存配置",
            "settings.api.complete": "当前配置完整，可直接发起请求。",
            "settings.api.incomplete": "还没有填写完整配置。",
            "settings.compatibility": "兼容说明",
            "settings.compatibility.1": "1. OpenAI 常用地址：`https://api.openai.com/v1/chat/completions`",
            "settings.compatibility.2": "2. DeepSeek 常用地址：`https://api.deepseek.com/chat/completions`",
            "settings.compatibility.3": "3. 如果你接的是自建兼容网关，也可以直接填完整 POST 地址。",
            "settings.knowledge.title": "知识库",
            "settings.knowledge.subtitle": "这里是用户自己维护的知识库。你可以写规则、业务背景、接口说明、风格要求，智能体和对话都会自动带上它。",
            "settings.knowledge.entryTitle": "知识库标题",
            "settings.knowledge.entryHint": "例如：项目规范 / 游戏玩法规则 / API 对接说明",
            "settings.knowledge.content": "知识库内容",
            "settings.knowledge.save": "保存到知识库",
            "settings.knowledge.update": "更新知识库",
            "settings.knowledge.clearEditor": "清空编辑框",
            "settings.knowledge.clearAll": "清空知识库",
            "settings.knowledge.empty": "还没有知识库条目。",
            "common.edit": "编辑",
            "common.delete": "删除",
            "settings.memory.title": "长期记忆",
            "settings.memory.subtitle": "应用会从你的输入和 Agent 任务里学习长期偏好，并在后续对话和自动化任务里继续使用。",
            "settings.memory.empty": "还没有学习到长期记忆。",
            "settings.memory.source": "来源：%@ · %@",
            "settings.memory.clear": "清空学习记忆",
            "settings.data.title": "数据管理",
            "settings.data.subtitle": "这个按钮只会清空本地会话、任务、日志、学习记忆和工作区引用，不会删除 API 配置。API 如需删除，请把设置里的字段清空后再点保存。",
            "settings.data.kbNote": "知识库也属于本地数据的一部分，点下面这个按钮时会一起清空，但不会删除你桌面工作区里的真实项目文件。",
            "settings.data.clear": "清空本地数据（保留 API）",
            "onboarding.badge": "首次使用引导",
            "onboarding.title": "让你的 Agent 更快进入状态",
            "onboarding.subtitle": "这个引导只会在第一次启动时出现。以后如果想再看，可以在设置里重新打开。",
            "onboarding.language.title": "选择语言",
            "onboarding.language.subtitle": "开始前先切换你习惯的界面语言。",
            "onboarding.step1.title": "1. 先填写 API 配置",
            "onboarding.step1.body": "打开设置，填入 API URL、API Key 和模型名称。OpenAI 兼容接口和 DeepSeek 兼容接口都支持。",
            "onboarding.step2.title": "2. 用聊天或任务来驱动",
            "onboarding.step2.body": "中间聊天窗口适合普通多轮对话；如果你已经知道目标，可以打开任务中心把目标保存成任务。",
            "onboarding.step3.title": "3. 用本地 Agent 自动执行",
            "onboarding.step3.body": "打开 Agent 模式后选一个工作区，再描述你想得到的结果。它可以建文件夹、生成多种文件、执行命令，并在原有代码上继续迭代。",
            "onboarding.step4.title": "4. 让它持续学习",
            "onboarding.step4.body": "你可以把规则放进知识库，应用也会从你的请求里保留长期记忆，让智能体越来越稳定。",
            "onboarding.tip": "现在代码类文件在落盘前，会尽量先做可用的语法预校验。",
            "onboarding.start": "开始使用 OpenDesk",
            "onboarding.close": "关闭引导",
            "status.configurationSaved": "配置已保存",
            "status.workspaceConnected": "已连接工作区",
            "status.desktopWorkspaceReady": "桌面工作区已准备好",
            "error.selectWorkspaceFirst": "请先选择工作区。",
            "error.kbEmpty": "知识库标题和内容都不能为空。",
            "status.kbSaved": "知识库已保存",
            "status.localDataCleared": "本地数据已清空，API 配置已保留",
            "status.stopping": "正在停止...",
            "error.taskEmpty": "任务内容不能为空。",
            "task.newTaskFallback": "新任务",
            "status.taskCreated": "任务已创建",
            "error.agentRunning": "智能体正在执行，请先等待完成或停止。",
            "error.replyRunning": "当前有回复正在生成，请先等待完成或点击停止。",
            "error.agentGoalEmpty": "请输入要自动执行的目标。",
            "error.apiIncomplete": "请先在设置中填写 API URL、API Key 和模型名称。",
            "error.chatRunning": "当前普通聊天还在生成，请先等待完成或停止。",
            "error.agentAlreadyRunning": "智能体已经在执行中了。",
            "error.createWorkspaceFailed": "无法创建桌面工作区。",
            "agent.log.goal": "任务目标",
            "agent.log.workspace": "工作区",
            "status.agentRunning": "智能体正在执行...",
            "status.agentDone": "智能体任务完成",
            "status.agentStopped": "智能体已停止",
            "agent.log.interrupted.title": "任务中断",
            "agent.log.interrupted.detail": "本次自动化执行已被停止。",
            "agent.log.runFailed": "执行失败",
            "status.stoppingAgent": "正在停止智能体...",
            "error.settingsFirst": "请先打开设置，填写 API URL、API Key 和模型名称。",
            "status.generatingReply": "正在生成回复...",
            "status.replyDone": "回复完成",
            "error.emptyModelResponse": "模型返回了空内容。",
            "status.replyStopped": "已停止生成",
            "error.taskCancelled": "任务已取消",
            "prompt.task.execute": "请把下面的内容当作一个待完成任务来执行。",
            "prompt.task.title": "任务标题：",
            "prompt.task.detail": "任务内容：",
            "prompt.task.requirements": "输出要求：\n1. 直接开始完成，不要重复题目。\n2. 如果需要假设，请先明确假设再继续。\n3. 结尾追加一个“结果总结”小节。",
            "prompt.system.memoryKB": "以下是从长期记忆和用户知识库中得到的上下文，请尽量持续遵守：\n%@",
            "conversation.agentTaskFallback": "Agent任务",
            "conversation.agentGoal": "Agent 目标：%@\n工作区：%@",
            "conversation.agentDone": "智能体执行完成。\n\n%@",
            "conversation.validationExitCode": "\n\n自检退出码：%d\n",
            "prompt.context.memory": "长期记忆：\n%@",
            "prompt.context.kb": "用户知识库：\n%@",
            "status.onboardingComplete": "引导已完成",
            "api.error.invalidURL": "API URL 无效，请检查设置页中的地址。",
            "api.error.invalidResponse": "服务器返回了无法识别的数据。",
            "api.error.requestFailed": "请求失败（%d）：%@",
            "api.error.emptyResponse": "模型没有返回内容。",
            "workspace.error.invalidPath": "工作区路径无效。",
            "workspace.error.outsideWorkspace": "目标路径超出了当前工作区。",
            "workspace.error.readFailed": "读取文件失败：%@",
            "workspace.error.writeFailed": "写入文件失败：%@",
            "agent.error.invalidPlan": "智能体计划格式无效：%@",
            "agent.error.exhaustedIterations": "智能体达到最大执行轮次，任务可能尚未完全完成。",
            "error.localSaveFailed": "本地保存失败：%@"
        ],
        .italian: [
            "conversation.new": "Nuova Chat",
            "preview.empty": "Nessun messaggio",
            "preview.preparing": "Preparazione della risposta...",
            "task.status.pending": "In attesa",
            "task.status.running": "In esecuzione",
            "task.status.completed": "Completato",
            "sidebar.tagline": "Il tuo spazio AI Agent per macOS",
            "sidebar.newConversation": "Nuova Chat",
            "sidebar.sessions": "Sessioni",
            "sidebar.deleteConversation": "Elimina Chat",
            "sidebar.pendingTasks": "Attivita %d",
            "sidebar.settings": "Impostazioni",
            "sidebar.workspace": "Workspace: %@",
            "chat.requestFailed": "Richiesta Fallita",
            "common.ok": "OK",
            "chat.defaultTitle": "Inizia a Creare",
            "chat.readySubtitle": "Supporta API compatibili con OpenAI / DeepSeek con risposte in streaming.",
            "chat.setupSubtitle": "Apri Impostazioni, completa la configurazione API e poi inizia a chattare.",
            "chat.tasks": "Attivita",
            "chat.newConversation": "Nuova Chat",
            "composer.title": "Messaggio",
            "composer.streaming": "Streaming in corso",
            "composer.multiTurn": "Chat multi-turno disponibile",
            "composer.task": "Attivita",
            "composer.stop": "Ferma",
            "composer.send": "Invia",
            "empty.title": "Inizia a Creare",
            "empty.readyDescription": "Scrivi un messaggio per iniziare la chat oppure invia l'idea al centro attivita e lascia eseguire l'Agent.",
            "empty.setupDescription": "Compila prima le informazioni API nelle Impostazioni, poi la chat in streaming sara disponibile.",
            "empty.openAgent": "Apri Agent",
            "empty.openTaskCenter": "Apri Centro Attivita",
            "empty.openSettings": "Apri Impostazioni",
            "message.you": "Tu",
            "message.ai": "AI",
            "message.generating": "Generazione progressiva in corso...",
            "taskCenter.title": "Centro Attivita",
            "taskCenter.subtitle": "Salva l'idea corrente come attivita oppure affidala direttamente al modello. Le attivita in esecuzione vengono riportate automaticamente nella chat.",
            "common.close": "Chiudi",
            "taskCenter.newTask": "Nuova Attivita",
            "taskCenter.taskTitleHint": "Titolo attivita (opzionale)",
            "taskCenter.prefillTip": "Suggerimento: se il compositore della chat contiene gia testo, aprendolo qui verra precompilato automaticamente.",
            "taskCenter.createTask": "Crea Attivita",
            "task.section.pending": "In attesa",
            "task.section.completed": "Completate",
            "task.none.pending": "Nessuna attivita in attesa.",
            "task.none.completed": "Nessuna attivita completata.",
            "task.button.run": "Esegui Attivita",
            "task.button.rerun": "Esegui di Nuovo",
            "task.button.markComplete": "Segna Completata",
            "task.button.markIncomplete": "Segna Non Completata",
            "task.linkedConversation": "Chat: %@",
            "agent.title": "Agent Locale",
            "agent.subtitle": "Dopo aver scelto un workspace, l'agente puo creare file, modificare codice, eseguire comandi e fare autoverifica in locale.",
            "agent.note": "Usa memoria a lungo termine e knowledge base dell'utente; i file di codice vengono pre-validati sintatticamente prima della scrittura quando possibile.",
            "agent.workspace": "Workspace",
            "agent.workspace.none": "Nessun workspace selezionato. Puoi usare il workspace desktop predefinito oppure scegliere manualmente una cartella progetto esistente.",
            "agent.useDesktop": "Usa Workspace Desktop",
            "agent.chooseFolder": "Scegli Cartella",
            "agent.openFinder": "Apri nel Finder",
            "agent.goal": "Obiettivo di Automazione",
            "agent.goalExample": "Esempio: genera un gioco 2D eseguibile nel workspace corrente; la prossima volta continua dal codice esistente aggiungendo collisioni, punteggio e menu.",
            "agent.lastSummary": "Ultimo riepilogo completamento: %@",
            "agent.running": "In esecuzione...",
            "agent.start": "Avvia Automazione",
            "agent.clearLogs": "Pulisci Log",
            "agent.logs": "Log di Esecuzione",
            "agent.noLogs": "Ancora nessun log. Dopo aver avviato un'attivita di automazione, qui compariranno creazione file, output dei comandi e risultati dell'autoverifica.",
            "agent.pickWorkspacePrompt": "Scegli Workspace",
            "settings.language.title": "Lingua",
            "settings.language.subtitle": "Cambia subito la lingua dell'app. L'interfaccia principale e la guida iniziale si aggiornano insieme.",
            "settings.onboarding.title": "Guida",
            "settings.onboarding.subtitle": "Puoi riaprire in qualsiasi momento la guida introduttiva per rivedere il flusso di lavoro.",
            "settings.onboarding.reopen": "Mostra di Nuovo la Guida",
            "settings.api.title": "Impostazioni API",
            "settings.api.subtitle": "Supporta API compatibili con OpenAI / DeepSeek. Puoi inserire l'endpoint completo oppure fermarti a `v1` e l'app completera automaticamente `chat/completions`.",
            "settings.api.urlHint": "Ad esempio https://api.openai.com/v1/chat/completions",
            "settings.api.reveal": "Mostra",
            "settings.api.hide": "Nascondi",
            "settings.modelName": "Nome Modello",
            "settings.modelNameHint": "Ad esempio gpt-4o-mini / deepseek-chat",
            "settings.api.save": "Salva Configurazione",
            "settings.api.complete": "Configurazione completa. Ora puoi inviare richieste.",
            "settings.api.incomplete": "Configurazione ancora incompleta.",
            "settings.compatibility": "Compatibilita",
            "settings.compatibility.1": "1. Endpoint OpenAI comune: `https://api.openai.com/v1/chat/completions`",
            "settings.compatibility.2": "2. Endpoint DeepSeek comune: `https://api.deepseek.com/chat/completions`",
            "settings.compatibility.3": "3. Se usi un gateway compatibile self-hosted, puoi inserire direttamente l'endpoint POST completo.",
            "settings.knowledge.title": "Knowledge Base",
            "settings.knowledge.subtitle": "Questa e una knowledge base gestita dall'utente. Puoi salvare regole, contesto di business, note API e requisiti di stile. Sia la chat sia l'agente la useranno automaticamente.",
            "settings.knowledge.entryTitle": "Titolo Knowledge Base",
            "settings.knowledge.entryHint": "Ad esempio: regole progetto / regole gameplay / note integrazione API",
            "settings.knowledge.content": "Contenuto Knowledge Base",
            "settings.knowledge.save": "Salva nella Knowledge Base",
            "settings.knowledge.update": "Aggiorna Knowledge Base",
            "settings.knowledge.clearEditor": "Pulisci Editor",
            "settings.knowledge.clearAll": "Svuota Knowledge Base",
            "settings.knowledge.empty": "Nessuna voce nella knowledge base.",
            "common.edit": "Modifica",
            "common.delete": "Elimina",
            "settings.memory.title": "Memoria a Lungo Termine",
            "settings.memory.subtitle": "L'app apprende preferenze di lungo periodo dai tuoi input e dalle attivita dell'Agent, e continua a usarle nelle chat e automazioni future.",
            "settings.memory.empty": "Ancora nessuna memoria appresa.",
            "settings.memory.source": "Fonte: %@ · %@",
            "settings.memory.clear": "Cancella Memoria Appresa",
            "settings.data.title": "Gestione Dati",
            "settings.data.subtitle": "Questo pulsante cancella solo chat locali, attivita, log, memoria appresa e riferimenti al workspace. Non elimina la configurazione API. Per rimuovere i dati API, svuota i campi qui e salva di nuovo.",
            "settings.data.kbNote": "Anche la knowledge base fa parte dei dati locali e verra cancellata, ma i veri file di progetto nel workspace desktop non verranno eliminati.",
            "settings.data.clear": "Cancella Dati Locali (Mantieni API)",
            "onboarding.badge": "Guida Primo Avvio",
            "onboarding.title": "Fai Partire il Tuo Agent Piu Velocemente",
            "onboarding.subtitle": "Questa guida appare solo al primo avvio. In seguito potrai riaprirla dalle Impostazioni quando vuoi.",
            "onboarding.language.title": "Scegli Lingua",
            "onboarding.language.subtitle": "Imposta la lingua dell'interfaccia prima di iniziare.",
            "onboarding.step1.title": "1. Compila le Impostazioni API",
            "onboarding.step1.body": "Apri Impostazioni e inserisci API URL, API Key e nome modello. Sono supportati sia endpoint compatibili con OpenAI sia con DeepSeek.",
            "onboarding.step2.title": "2. Usa Chat o Attivita",
            "onboarding.step2.body": "La vista chat centrale e ideale per conversazioni multi-turno normali. Se conosci gia l'obiettivo, apri il Centro Attivita e salvalo come task.",
            "onboarding.step3.title": "3. Usa la Modalita Agent Locale",
            "onboarding.step3.body": "Apri la modalita Agent, scegli un workspace e descrivi il risultato desiderato. L'agente puo creare cartelle, generare molti tipi di file, eseguire comandi e continuare a iterare sul codice esistente.",
            "onboarding.step4.title": "4. Lascialo Imparare",
            "onboarding.step4.body": "Metti regole nella knowledge base e l'app conservera anche memoria a lungo termine dalle tue richieste, cosi l'agente diventera sempre piu coerente.",
            "onboarding.tip": "Per i file di codice, l'agente esegue ora la validazione sintattica disponibile prima di scrivere quando possibile.",
            "onboarding.start": "Inizia a Usare OpenDesk",
            "onboarding.close": "Chiudi Guida",
            "status.configurationSaved": "Configurazione salvata",
            "status.workspaceConnected": "Workspace collegato",
            "status.desktopWorkspaceReady": "Workspace desktop pronto",
            "error.selectWorkspaceFirst": "Seleziona prima un workspace.",
            "error.kbEmpty": "Titolo e contenuto della knowledge base non possono essere vuoti.",
            "status.kbSaved": "Knowledge base salvata",
            "status.localDataCleared": "Dati locali cancellati. La configurazione API e stata mantenuta.",
            "status.stopping": "Arresto in corso...",
            "error.taskEmpty": "Il contenuto dell'attivita non puo essere vuoto.",
            "task.newTaskFallback": "Nuova Attivita",
            "status.taskCreated": "Attivita creata",
            "error.agentRunning": "L'agente e in esecuzione. Attendi il completamento oppure fermalo prima.",
            "error.replyRunning": "Una risposta e ancora in generazione. Attendi oppure premi Ferma.",
            "error.agentGoalEmpty": "Inserisci un obiettivo di automazione.",
            "error.apiIncomplete": "Compila prima API URL, API Key e nome modello nelle Impostazioni.",
            "error.chatRunning": "Una normale risposta chat e ancora in corso. Attendi oppure fermala prima.",
            "error.agentAlreadyRunning": "L'agente e gia in esecuzione.",
            "error.createWorkspaceFailed": "Impossibile creare il workspace desktop.",
            "agent.log.goal": "Obiettivo",
            "agent.log.workspace": "Workspace",
            "status.agentRunning": "Agent in esecuzione...",
            "status.agentDone": "Attivita Agent completata",
            "status.agentStopped": "Agent fermato",
            "agent.log.interrupted.title": "Attivita Interrotta",
            "agent.log.interrupted.detail": "Questa esecuzione di automazione e stata fermata.",
            "agent.log.runFailed": "Esecuzione Fallita",
            "status.stoppingAgent": "Arresto dell'agent...",
            "error.settingsFirst": "Apri prima Impostazioni e inserisci API URL, API Key e nome modello.",
            "status.generatingReply": "Generazione risposta...",
            "status.replyDone": "Risposta completata",
            "error.emptyModelResponse": "Il modello ha restituito un contenuto vuoto.",
            "status.replyStopped": "Generazione interrotta",
            "error.taskCancelled": "Attivita annullata",
            "prompt.task.execute": "Tratta il seguente contenuto come un'attivita da completare.",
            "prompt.task.title": "Titolo attivita:",
            "prompt.task.detail": "Dettaglio attivita:",
            "prompt.task.requirements": "Requisiti di output:\n1. Inizia direttamente a risolvere senza ripetere il titolo.\n2. Se ti servono ipotesi, dichiarale chiaramente prima e poi continua.\n3. Chiudi con una breve sezione \"Riepilogo Risultato\".",
            "prompt.system.memoryKB": "Il seguente contesto proviene dalla memoria a lungo termine e dalla knowledge base dell'utente. Cerca di seguirlo in modo coerente:\n%@",
            "conversation.agentTaskFallback": "Task Agent",
            "conversation.agentGoal": "Obiettivo Agent: %@\nWorkspace: %@",
            "conversation.agentDone": "Esecuzione dell'agent completata.\n\n%@",
            "conversation.validationExitCode": "\n\nCodice uscita validazione: %d\n",
            "prompt.context.memory": "Memoria a lungo termine:\n%@",
            "prompt.context.kb": "Knowledge base utente:\n%@",
            "status.onboardingComplete": "Guida completata",
            "api.error.invalidURL": "L'URL API non e valido. Controlla l'indirizzo nelle Impostazioni.",
            "api.error.invalidResponse": "Il server ha restituito dati non riconoscibili.",
            "api.error.requestFailed": "Richiesta fallita (%d): %@",
            "api.error.emptyResponse": "Il modello non ha restituito contenuto.",
            "workspace.error.invalidPath": "Il percorso del workspace non e valido.",
            "workspace.error.outsideWorkspace": "Il percorso di destinazione e fuori dal workspace corrente.",
            "workspace.error.readFailed": "Lettura file fallita: %@",
            "workspace.error.writeFailed": "Scrittura file fallita: %@",
            "agent.error.invalidPlan": "Il formato del piano dell'agent non e valido: %@",
            "agent.error.exhaustedIterations": "L'agent ha raggiunto il numero massimo di iterazioni e potrebbe non aver finito del tutto.",
            "error.localSaveFailed": "Salvataggio locale fallito: %@"
        ]
    ]
}

extension View {
    func appCard(fill: Color = AppTheme.panel) -> some View {
        background(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .fill(fill)
                .overlay(
                    RoundedRectangle(cornerRadius: 20, style: .continuous)
                        .stroke(AppTheme.border, lineWidth: 1)
                )
        )
    }
}
